return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	main = "nvim-treesitter.configs",
	opts = {
		ensure_installed = {
			"json",
			"javascript",
			"typescript",
			"tsx",
			"yaml",
			"html",
			"css",
			"markdown",
			"markdown_inline",
			"bash",
			"lua",
			"vim",
			"dockerfile",
			"gitignore",
			"nix",
			"c",
			"rust",
			"elixir",
			"java",
			"zig",
		},
		auto_install = true,
		highlight = {
			enable = true,
			additional_vim_regex_highlighting = {},
		},
		indent = {
			enable = true,
		},
	},
}
